import type { Property } from "@/src/types/property";

export const propertyImages = {
  exterior: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=88",
  living: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=88",
  house: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1800&q=88",
  kitchen: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=88",
  facade: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1800&q=88",
  dining: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=88",
};

export const mockProperties: Property[] = [
  {
    id: "alto-das-palmeiras",
    codigo: "1001",
    titulo: "Residência Alto das Palmeiras",
    tipo: "casa",
    preco: 2450000,
    cep: "06454-000",
    endereco: "Alameda dos Ipês, 184",
    bairro: "Alphaville",
    cidade: "Barueri",
    estado: "SP",
    descricao: "Uma residência contemporânea pensada para quem valoriza luz natural, privacidade e encontros memoráveis. A área social se abre para o jardim com piscina, enquanto a ala íntima reúne suítes amplas e acabamentos de alto padrão.",
    area: 420,
    quartos: 4,
    banheiros: 5,
    vagas: 4,
    imagens: [propertyImages.exterior, propertyImages.living, propertyImages.kitchen],
    destaque: true,
    criado_em: "2026-07-24T12:00:00Z",
  },
  {
    id: "jardins-essence",
    codigo: "1002",
    titulo: "Apartamento Jardins Essence",
    tipo: "apartamento",
    preco: 1890000,
    cep: "01414-002",
    endereco: "Rua Haddock Lobo, 920",
    bairro: "Jardins",
    cidade: "São Paulo",
    estado: "SP",
    descricao: "Apartamento reformado com planta generosa, marcenaria sob medida e vista livre. Ambientes integrados equilibram sofisticação e praticidade a poucos passos dos melhores serviços do bairro.",
    area: 186,
    quartos: 3,
    banheiros: 4,
    vagas: 2,
    imagens: [propertyImages.living, propertyImages.dining, propertyImages.kitchen],
    destaque: true,
    criado_em: "2026-07-18T12:00:00Z",
  },
  {
    id: "villa-serena",
    codigo: "1003",
    titulo: "Casa Villa Serena",
    tipo: "casa",
    preco: 3200000,
    cep: "06709-320",
    endereco: "Rua das Acácias, 62",
    bairro: "Granja Viana",
    cidade: "Cotia",
    estado: "SP",
    descricao: "Arquitetura limpa, materiais naturais e uma relação fluida entre interior e paisagismo. A casa oferece espaço gourmet completo, escritório, home theater e quatro suítes.",
    area: 510,
    quartos: 4,
    banheiros: 6,
    vagas: 5,
    imagens: [propertyImages.house, propertyImages.exterior, propertyImages.dining],
    destaque: true,
    criado_em: "2026-07-10T12:00:00Z",
  },
  {
    id: "reserva-do-lago",
    codigo: "1004",
    titulo: "Lote Reserva do Lago",
    tipo: "lote",
    preco: 780000,
    cep: "06543-001",
    endereco: "Alameda do Lago, lote 14",
    bairro: "Tamboré",
    cidade: "Santana de Parnaíba",
    estado: "SP",
    descricao: "Lote plano em condomínio consolidado, com excelente orientação solar, frente ampla e projeto paisagístico integrado às áreas comuns.",
    area: 620,
    quartos: 0,
    banheiros: 0,
    vagas: 0,
    imagens: [propertyImages.facade, propertyImages.exterior],
    destaque: false,
    criado_em: "2026-06-22T12:00:00Z",
  },
  {
    id: "loft-paulista",
    codigo: "1005",
    titulo: "Loft Paulista 360",
    tipo: "apartamento",
    preco: 980000,
    cep: "01419-001",
    endereco: "Alameda Santos, 1410",
    bairro: "Bela Vista",
    cidade: "São Paulo",
    estado: "SP",
    descricao: "Loft urbano com pé-direito alto, varanda e serviços completos no condomínio. Ideal para viver ou investir em uma localização estratégica.",
    area: 74,
    quartos: 1,
    banheiros: 2,
    vagas: 1,
    imagens: [propertyImages.kitchen, propertyImages.living],
    destaque: false,
    criado_em: "2026-06-10T12:00:00Z",
  },
  {
    id: "casa-horizonte",
    codigo: "1006",
    titulo: "Casa Horizonte",
    tipo: "casa",
    preco: 1650000,
    cep: "13049-107",
    endereco: "Rua Horizonte Azul, 48",
    bairro: "Swiss Park",
    cidade: "Campinas",
    estado: "SP",
    descricao: "Casa nova em condomínio, com ambientes integrados, energia solar, piscina aquecida e uma suíte térrea versátil.",
    area: 280,
    quartos: 4,
    banheiros: 4,
    vagas: 3,
    imagens: [propertyImages.facade, propertyImages.dining],
    destaque: false,
    criado_em: "2026-05-27T12:00:00Z",
  },
];
