begin;

with incoming (id, nome, categoria, tipos_aplicaveis) as (
  values
    ('aquecimento_eletrico', 'Aquecimento elétrico', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('aquecimento_gas', 'Aquecimento a gás', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('aquecimento_solar', 'Aquecimento solar', 'interna', array['casa','chacara','sitio']::text[]),
    ('ar_condicionado', 'Ar condicionado', 'interna', array['apartamento','casa','chacara','cobertura','galpao','loja','predio','sala','sitio']::text[]),
    ('armario_cozinha', 'Armário na cozinha', 'interna', array['apartamento','casa','chacara','cobertura','sitio']::text[]),
    ('armarios_embutidos', 'Armários embutidos', 'interna', array['apartamento','casa','chacara','cobertura','sitio','sala']::text[]),
    ('area_servico', 'Área de serviço', 'interna', array['apartamento','casa','chacara','cobertura','sitio']::text[]),
    ('banheiro_comercial', 'Banheiro', 'interna', array['loja','sala']::text[]),
    ('box_banheiro', 'Box no banheiro', 'interna', array['apartamento','casa','chacara','cobertura','sitio']::text[]),
    ('casa_maquinas', 'Casa de máquinas', 'interna', array['predio']::text[]),
    ('closet', 'Closet', 'interna', array['apartamento','casa','chacara','cobertura','sitio']::text[]),
    ('copa_kitchenette', 'Copa / Kitchenette', 'interna', array['loja','sala']::text[]),
    ('cozinha_planejada', 'Cozinha planejada', 'interna', array['apartamento','casa','chacara','cobertura','sitio']::text[]),
    ('conexao_internet_fibra', 'Conexão internet (fibra)', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('deposito_despensa', 'Depósito / Despensa', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('deposito_interno', 'Depósito interno', 'interna', array['loja','sala']::text[]),
    ('divisorias', 'Divisórias', 'interna', array['loja','sala']::text[]),
    ('escada_incendio', 'Escada de incêndio', 'interna', array['predio']::text[]),
    ('escritorio_home_office', 'Escritório / Home office', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('escritorio_interno', 'Escritório interno', 'interna', array['galpao']::text[]),
    ('forro_gesso', 'Forro de gesso', 'interna', array['loja','sala']::text[]),
    ('iluminacao_industrial', 'Iluminação industrial', 'interna', array['galpao']::text[]),
    ('janelas_antirruido', 'Janelas antirruído', 'interna', array['apartamento','cobertura','sala']::text[]),
    ('lareira', 'Lareira', 'interna', array['casa','chacara','sitio']::text[]),
    ('lavabo', 'Lavabo', 'interna', array['apartamento','casa','chacara','cobertura','sitio','loja','sala']::text[]),
    ('lavanderia', 'Lavanderia', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('mezanino', 'Mezanino', 'interna', array['casa','chacara','sitio','galpao']::text[]),
    ('piso_industrial', 'Piso industrial', 'interna', array['galpao']::text[]),
    ('piso_laminado', 'Piso laminado', 'interna', array['apartamento','cobertura','sala']::text[]),
    ('piso_porcelanato', 'Piso porcelanato', 'interna', array['apartamento','cobertura','sala','loja']::text[]),
    ('porao', 'Porão', 'interna', array['casa','chacara','sitio']::text[]),
    ('rede_eletrica_trifasica', 'Rede elétrica trifásica', 'interna', array['galpao']::text[]),
    ('refeitorio', 'Refeitório', 'interna', array['galpao']::text[]),
    ('rouparia', 'Rouparia', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('sacada', 'Sacada', 'interna', array['apartamento','cobertura','sala','casa','chacara','sitio']::text[]),
    ('sauna', 'Sauna', 'interna', array['apartamento','casa','chacara','cobertura','sitio']::text[]),
    ('sistema_exaustao', 'Sistema de exaustão', 'interna', array['galpao']::text[]),
    ('sotao', 'Sótão', 'interna', array['casa','chacara','sitio']::text[]),
    ('terraco_gourmet', 'Terraço gourmet', 'interna', array['apartamento','cobertura','sala']::text[]),
    ('vestiario', 'Vestiário', 'interna', array['galpao']::text[]),
    ('vista_mar', 'Vista para o mar', 'interna', array['apartamento','cobertura','sala']::text[]),
    ('vista_montanha', 'Vista para montanha', 'interna', array['apartamento','cobertura','sala']::text[]),
    ('vista_panoramica', 'Vista panorâmica', 'interna', array['apartamento','cobertura','sala']::text[]),
    ('vitrine', 'Vitrine', 'interna', array['loja','sala']::text[]),
    ('academia', 'Academia', 'externa', array['apartamento','cobertura','predio','sala']::text[]),
    ('acesso_carga_descarga', 'Acesso para carga / descarga', 'externa', array['loja','sala']::text[]),
    ('area_gourmet_externa', 'Área gourmet externa', 'externa', array['casa','chacara','sitio']::text[]),
    ('area_mata_nativa', 'Área de mata nativa', 'externa', array['chacara','sitio']::text[]),
    ('asfalto_pavimentacao', 'Asfalto / Pavimentação', 'externa', array['lote','lote_condominio']::text[]),
    ('bicicletario', 'Bicicletário', 'externa', array['apartamento','cobertura']::text[]),
    ('campo_futebol', 'Campo de futebol', 'externa', array['chacara','sitio']::text[]),
    ('casa_caseiro', 'Casa de caseiro', 'externa', array['chacara','sitio']::text[]),
    ('cerca', 'Cerca', 'externa', array['chacara','sitio']::text[]),
    ('cerca_eletrica', 'Cerca elétrica', 'externa', array['casa','chacara','sitio']::text[]),
    ('cerca_muro_perimetral', 'Cerca / Muro perimetral', 'externa', array['galpao']::text[]),
    ('churrasqueira', 'Churrasqueira', 'externa', array['apartamento','casa','chacara','cobertura','sitio','lote_condominio']::text[]),
    ('cftv', 'Circuito interno de TV (CFTV)', 'externa', array['apartamento','cobertura','casa','loja','sala','predio']::text[]),
    ('condominio_fechado', 'Condomínio fechado', 'externa', array['apartamento','cobertura','predio','sala','casa','lote_condominio']::text[]),
    ('coworking', 'Coworking', 'externa', array['apartamento','cobertura']::text[]),
    ('curral', 'Curral', 'externa', array['chacara','sitio']::text[]),
    ('doca_carga', 'Doca de carga', 'externa', array['galpao']::text[]),
    ('edicula', 'Edícula', 'externa', array['casa']::text[]),
    ('energia_eletrica_propria', 'Energia elétrica própria', 'externa', array['chacara','sitio']::text[]),
    ('energia_solar', 'Energia solar', 'externa', array['casa','chacara','sitio','galpao','loja','predio']::text[]),
    ('energia_trifasica_externa', 'Energia trifásica externa', 'externa', array['galpao']::text[]),
    ('elevador', 'Elevador', 'externa', array['apartamento','cobertura','predio','sala']::text[]),
    ('espaco_gourmet', 'Espaço gourmet', 'externa', array['apartamento','cobertura']::text[]),
    ('espaco_pet', 'Espaço pet', 'externa', array['apartamento','cobertura']::text[]),
    ('estacionamento', 'Estacionamento', 'externa', array['loja','sala']::text[]),
    ('estacionamento_caminhoes', 'Estacionamento de caminhões', 'externa', array['galpao']::text[]),
    ('estacionamento_proprio', 'Estacionamento próprio', 'externa', array['predio']::text[]),
    ('estrada_acesso', 'Estrada de acesso', 'externa', array['chacara','sitio']::text[]),
    ('fachada_propria', 'Fachada própria', 'externa', array['loja','sala']::text[]),
    ('fossa_septica', 'Fossa séptica', 'externa', array['casa','chacara','sitio']::text[]),
    ('galpao_deposito', 'Galpão / Depósito', 'externa', array['chacara','sitio']::text[]),
    ('garagem_coberta', 'Garagem coberta', 'externa', array['casa','chacara','sitio']::text[]),
    ('gerador', 'Gerador', 'externa', array['apartamento','cobertura','casa','predio']::text[]),
    ('guarita', 'Guarita', 'externa', array['galpao']::text[]),
    ('horta', 'Horta', 'externa', array['casa','chacara','sitio']::text[]),
    ('jardim', 'Jardim', 'externa', array['casa','chacara','sitio','predio']::text[]),
    ('meio_fio', 'Meio-fio', 'externa', array['lote','lote_condominio']::text[]),
    ('muro_alto', 'Muro alto', 'externa', array['casa']::text[]),
    ('muro_divisa', 'Muro de divisa', 'externa', array['lote','lote_condominio']::text[]),
    ('nascente_agua', 'Nascente d''água', 'externa', array['chacara','sitio']::text[]),
    ('pasto', 'Pasto', 'externa', array['chacara','sitio']::text[]),
    ('patio_manobra', 'Pátio de manobra', 'externa', array['galpao']::text[]),
    ('piscina', 'Piscina', 'externa', array['apartamento','casa','chacara','cobertura','sitio','lote_condominio']::text[]),
    ('poco_artesiano', 'Poço artesiano', 'externa', array['casa','chacara','sitio']::text[]),
    ('pomar', 'Pomar', 'externa', array['casa','chacara','sitio']::text[]),
    ('playground', 'Playground', 'externa', array['apartamento','cobertura']::text[]),
    ('portao_caminhao', 'Portão para caminhão', 'externa', array['galpao']::text[]),
    ('portao_eletronico', 'Portão eletrônico', 'externa', array['apartamento','casa','chacara','cobertura','galpao','loja','predio','sala','sitio','lote_condominio']::text[]),
    ('portaria', 'Portaria', 'externa', array['loja','sala','predio']::text[]),
    ('portaria_24h', 'Portaria 24h', 'externa', array['apartamento','cobertura','lote_condominio']::text[]),
    ('quadra_poliesportiva', 'Quadra poliesportiva', 'externa', array['apartamento','cobertura']::text[]),
    ('quintal', 'Quintal', 'externa', array['casa','chacara','sitio']::text[]),
    ('quiosque', 'Quiosque', 'externa', array['chacara','sitio']::text[]),
    ('rede_agua', 'Rede de água', 'externa', array['lote','lote_condominio']::text[]),
    ('rede_eletrica_disponivel', 'Rede elétrica disponível', 'externa', array['lote','lote_condominio']::text[]),
    ('rede_esgoto', 'Rede de esgoto', 'externa', array['lote','lote_condominio']::text[]),
    ('represa_acude', 'Represa / Açude', 'externa', array['chacara','sitio']::text[]),
    ('reservatorio_agua', 'Reservatório de água próprio', 'externa', array['predio']::text[]),
    ('salao_festas', 'Salão de festas', 'externa', array['apartamento','cobertura','predio','sala']::text[]),
    ('sistema_energia_solar', 'Sistema de energia solar', 'externa', array['apartamento','cobertura']::text[]),
    ('acesso_pcd', 'Acesso para PCD', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','predio','sala','sitio']::text[]),
    ('aceita_financiamento', 'Aceita financiamento', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('aceita_permuta', 'Aceita permuta', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('alvara_funcionamento', 'Alvará de funcionamento', 'geral', array['loja','sala']::text[]),
    ('area_preservacao_proxima', 'Área de preservação próxima', 'geral', array['lote','lote_condominio']::text[]),
    ('documentacao_regularizada', 'Documentação regularizada', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('fachada_comercial', 'Fachada comercial', 'geral', array['galpao','loja','predio','sala']::text[]),
    ('fluxo_pessoas_alto', 'Fluxo de pessoas alto', 'geral', array['loja','sala']::text[]),
    ('habite_se', 'Habite-se emitido', 'geral', array['predio']::text[]),
    ('interfone', 'Interfone', 'geral', array['apartamento','cobertura','predio','sala','casa']::text[]),
    ('mobiliado', 'Mobiliado', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('pe_direito_alto', 'Pé-direito alto', 'geral', array['galpao']::text[]),
    ('proximo_comercio_escolas', 'Próximo a comércio/escolas', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('proximo_rodovia', 'Próximo a rodovia', 'geral', array['galpao']::text[]),
    ('proximo_transporte_publico', 'Próximo a transporte público', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('rua_asfaltada', 'Rua asfaltada', 'geral', array['casa']::text[]),
    ('semimobiliado', 'Semimobiliado', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','lote','lote_condominio','predio','sala','sitio']::text[]),
    ('sistema_seguranca', 'Sistema de segurança', 'geral', array['apartamento','casa','chacara','cobertura','galpao','loja','predio','sala','sitio','lote_condominio']::text[]),
    ('uso_misto', 'Uso misto (comercial / residencial)', 'geral', array['predio']::text[]),
    ('vista_privilegiada', 'Vista privilegiada', 'geral', array['lote','lote_condominio']::text[]),
    ('zoneamento_industrial', 'Zoneamento industrial', 'geral', array['galpao']::text[])
),
updated as (
  update public.caracteristicas as current
  set
    nome = incoming.nome,
    categoria = incoming.categoria,
    tipos_aplicaveis = incoming.tipos_aplicaveis
  from incoming
  where current.id = incoming.id
     or lower(current.nome) = lower(incoming.nome)
  returning current.id
)
insert into public.caracteristicas (id, nome, categoria, tipos_aplicaveis)
select incoming.id, incoming.nome, incoming.categoria, incoming.tipos_aplicaveis
from incoming
where not exists (
  select 1
  from public.caracteristicas as current
  where current.id = incoming.id
     or lower(current.nome) = lower(incoming.nome)
)
on conflict (id) do update set
  nome = excluded.nome,
  categoria = excluded.categoria,
  tipos_aplicaveis = excluded.tipos_aplicaveis;

commit;
